#! /bin/tcsh -f

# This the main NetMHCpan 4.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2017 April 23	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCpan 4.0 directory (mandatory)
setenv	NMHOME	/N/u/johnstrs/BigRed2/neoantigen_proj/netMHCpan-4.0

# determine where to store temporary files (must be writable to all users)
echo $*
echo $argv[2-$#argv]
if ( ${?TMPDIR} == 0 ) then
	setenv TMPDIR $NMHOME/$1
	#setenv  TMPDIR  /scratch      #Original
endif
mkdir $TMPDIR
# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`


###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCpan $NMHOME/$PLATFORM

# main ========================================================================
if ( -x $NETMHCpan/bin/netMHCpan ) then
   $NETMHCpan/bin/netMHCpan $argv[2-$#argv]
else
   echo netMHCpan: no binaries found for $PLATFORM $NETMHCpan/bin/netMHCpan
endif

# end of script ===============================================================
